vich_uploader:
    db_driver: orm

    mappings:
        lessons:
            uri_prefix: /images/lessons
            upload_destination: '%kernel.project_dir%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

